### PR TITLE
Add statuses/lookup method

### PR DESCRIPTION
**Pull request by soaxelbrooke**
Adds multi-tweet lookup method for fetching multiple tweets in one API call.

---
This change is [Reviewable](https://reviewable.io/reviews/bear/python-twitter/511)

### CODE REVIEW

**Comment by jeremylow** [comment]
LGTM!

**Comment by jeremylow** [comment]
Huh, there's a pending pull request on this endpoint, but that looks like it's got some legacy code for App Only Auth. Sorry about that. I'll try to parse out what the difference is; we may be able to combine them.

**Comment by Raj-JainHC** [comment]
When is this getting merged. Need for speed.

**Comment by Raj-JainHC** [comment]
@bear any updates?

**Comment by jeremylow** [comment]
I'm going to close this since the prior PR was accepted and merged for this endpoint. You should now be able to access these functions via the GetStatuses endpoint. This is available as of https://github.com/bear/python-twitter/releases/tag/v3.4

**Pull request closed without merging**
