### PR TITLE
Adding language support to GetStreamFilter in api.py. Also added the example for that.

### PR DESCRIPTION
**Pull request by chaitanya0411**
This is my first contribution to somebody else's repository, so please pardon me if I have made some blunder :)

---
This change is [Reviewable](https://reviewable.io/reviews/bear/python-twitter/401)

### CODE REVIEW

**Comment by jeremylow** [comment]
Looks pretty good! A couple things I'd like to see:
* Could you update doc/changelog.rst to note the change?
* Since it's only a few lines different in `track_users.py`, it may make sense to incorporate the changes on lines 20, 57, & 71 into the existing file. That way if we have to update the examples, we just make changes in one place.

Let me know what you think on # 2.

**Comment by jeremylow** [comment]
(Don't worry about the code coverage thing - that function isn't tested yet anyway.)

**Comment by jeremylow** [comment]
Looks great! Thanks for your help! @bear you good with this?

**Comment by bear** [comment]
Reviewed 2 of 3 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[twitter/api.py, line 4455 at r2](https://reviewable.io:443/reviews/bear/python-twitter/401#-KVavheXHGSPjftqF6sH:-KVavheXHGSPjftqF6sI:bk9jy0k) ([raw file](https://github.com/bear/python-twitter/blob/2b25d707932f01f51767b5b9ff8129941a7c5ef5/twitter/api.py#L4455)):*
> ```Python
>                         track=None,
>                         locations=None,
>                         languages=None,
> ```

my only quibble is that the new parameter be added to the end because we are doing this in a point release. 

if we add it into the middle of the parameter list then we break anyone who doesn't use named parameters in their calls.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bear/python-twitter/401)*

**Comment by jeremylow** [comment]
Crap, I did the same thing with PostStatus in #394

**Comment by bear** [comment]
@jeremylow ugh, sorry for not catching that! the benefit of smaller sized PRs

**Comment by jeremylow** [comment]
Yep. I'll fix it on `develop`.

**Comment by jeremylow** [comment]
Speaking of develop, I just noticed this is going into the master branch, so I switched it to get integrated with the rest of the changes for 3.2.

**Comment by bear** [comment]
with that param change i'm +1 on merging - nicely done!

**Comment by jeremylow** [comment]
Awesome. Merged! Thanks @chaitanya0411 and congrats on your first PR!

**Comment by chaitanya0411** [comment]
Thanks guys ! It was a good experience !
I hope there are more PR to come from me...
Also, as mentioned at https://python-twitter.readthedocs.io/en/latest/getting_started.html ,
I would like to check a [link](https://github.com/chaitanya0411/TheTweetsWatch) to my example application that I built using python-twitter.
Please free to comment or link it as an example ! Thanks again :)

**Pull request merged**
