### PR TITLE
Add support for getting places using Geo API and Place models

### PR DESCRIPTION
**Pull request by tuftedocelot**
I based the Place model and tests after the User/Status models/tests. If there's anything that should be adjusted or added, please let me know

---
This change is [Reviewable](https://reviewable.io/reviews/bear/python-twitter/574)

### CODE REVIEW

**Comment by tuftedocelot** [comment]
You know what, I forgot to link up Place to Status...stand by...

**Comment by tuftedocelot** [comment]
aaand I just discovered https://github.com/bear/python-twitter/issues/342 and the api_coverage branch, so I'm not sure what should be done with this now

**Comment by jeremylow** [comment]
Tests don't pass with python 2.7 because of the AsJsonString() method. It's being skipped in python3 for some reason (I think this mirrors an old issue with the testing of statuses, which is where it probably crept in). The offending line is here: https://github.com/bear/python-twitter/pull/574/files#diff-9818e8d92e07b71e42c9e76e600833b5R85

Otherwise, looks good. I don't see a Place model in the api_coverage branch, but I honestly kind of forgot that was still hanging around. I think a fair chunk of it has been merged into master at this point, but I have no issue abandoning that version for this.

One last thing would be to have a set of tests for GetPlace and attaching a Place to a status that use `responses`, something like https://github.com/bear/python-twitter/blob/master/tests/test_direct_messages.py#L30 so we can ensure that making the calls to the API is covered as well as the model itself.

**Comment by tuftedocelot** [comment]
@jeremylow, I'm not sure what to do with the Python 2.7 test failure. I had updated the existing status test which includes the status with unicode characters.

Are the new tests more of what you had in mind?

**Review by bear — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 2 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bear/python-twitter/574)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jeremylow)

**Review by bear — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bear/python-twitter/574)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jeremylow)

**Pull request merged**
