### PR TITLE
Get statuses

### PR DESCRIPTION
**Pull request by jschultz**
This change adds a function to access the `GET statuses/lookup` API to hydrate multiple tweets. The method `GetStatuses` automatically splits a list of ids into batches of 100, as that is the maximum handled by the API.

---
This change is [Reviewable](https://reviewable.io/reviews/bear/python-twitter/460)

### CODE REVIEW

**Comment by jeremylow** [comment]
Hey, this looks awesome. Thanks! I had a few things:

* I'd like to keep the nomenclature consistent around `status_id(s)` to the extent possible, so that kwargs are predictable for folks just coming to the API. (This also helps to avoid the linting issue with shadowing the builtin `id`, for example on [line 861](https://github.com/bear/python-twitter/pull/460/files#diff-ca47863eef03007ed84692b07b74eda6R861) and [852](https://github.com/bear/python-twitter/pull/460/files#diff-ca47863eef03007ed84692b07b74eda6R852)
* Twitter has a `map` parameter [here](https://dev.twitter.com/rest/reference/get/statuses/lookup), that should be supported.
* Since this is a new public method, we should include tests. If you have any questions about the testing framework, let me know. (I've been meaning to write up some documentation on that, but it keeps getting pushed back.)

**Comment by jschultz** [comment]
I've responded to your first two points. On the second I was surprised to see that the `map` parameter does rather more than the description in the the Twitter API doc. In fact it returns a dictionary with tweet ID as key and content as value. This functionality removes the rationale for writing my own code to return an ordered list, so I got rid of that. There are still two quirks I can see:

1. Returning entirely different data structures (list or dict) depending on the value of the parameter `map` is a bit ugly. But that is how the API works.
2. The dictionary returned by the API uses the tweet ID as Unicode, which I have found can lead to sorting problems with very old tweets (ie those with fewer than 18 digits in their ID). I therefore convert the ID to int while building the dictionary to return.

As far as the testing framework goes, I had a look and think I can pretty easily write some tests modelled on existing ones. But I'd rather we agree on the functionality before I go down that path.

**Comment by jeremylow** [comment]
1. Yeah, I agree that's a little weird, but it is what it is. I think returning different data structures is fine so long as it's noted in the doc string. We could use an `OrderedDict` if you think that makes sense too.
2. Weird, but I agree that converting to `int`s makes sense.

Here's a Debug subclass of the Api if you want to get the raw response bodies for getting testing data (github won't let me just upload the .py file): 

```python
from twitter import Api, TwitterError
import requests


class DebugAPI(Api):
    def DebugEndpoint(self, verb=None, endpoint=None, data=None):
        """ Request a url and return raw data. For testing purposes only.

        Args:
            url:
                The web location we want to retrieve.
            verb:
                Either POST or GET.
            data:
                A dict of (str, unicode) key/value pairs.

        Returns:
            data
        """

        url = "{0}{1}".format(self.base_url, endpoint)

        if verb == 'POST':
            if 'media_ids' in data:
                url = self._BuildUrl(
                    url,
                    extra_params={
                        'media_ids': data['media_ids']
                    }
                )
                print('POSTing url:', url)
            if 'media' in data:
                try:
                    print('POSTing url:', url)
                    raw_data = requests.post(
                        url,
                        files=data,
                        auth=self.__auth,
                        timeout=self._timeout
                    )
                except requests.RequestException as e:
                    raise TwitterError(str(e))
            else:
                try:
                    print('POSTing url:', url)
                    raw_data = requests.post(
                        url,
                        data=data,
                        auth=self.__auth,
                        timeout=self._timeout
                    )
                except requests.RequestException as e:
                    raise TwitterError(str(e))
        if verb == 'GET':
            url = self._BuildUrl(url, extra_params=data)
            print('GETting url:', url)
            try:
                raw_data = requests.get(
                    url,
                    auth=self.__auth,
                    timeout=self._timeout)

            except requests.RequestException as e:
                raise TwitterError(str(e))
        return raw_data._content
```

**Comment by jschultz** [comment]
I plan to just model tests based on those for GetStatus() which does not appear to use the debug API.

One issue is that to test the batch processing in GetStatuses() you need at least 100 tweets to retrieve. I suppose I could just generate some list of tweet IDs and initialise a Python list with them as elements. But this will take many lines of the test code. The test also risks failing if any of those tweets is deleted. Or we could create a test Twitter account and write a bunch of tweets to keep for testing. Any suggestions?

**Comment by bear** [comment]
@jeremylow I finally have some free time and working thru items - is there anything preventing this pull request from being merged?

**Comment by jeremylow** [comment]
Sorry, just getting my head above water @bear . I don't think so, but I'll look at it this week and confirm. I think it's good to go, but it's also been a while for me.

**Comment by gmiretti** [comment]
@jeremylow @bear How can I help you to merge this PR or #511 and release a new version?

**Pull request merged**
