### PR TITLE
Updates to documentation and makefile

### PR DESCRIPTION
**Pull request by jeremylow**
I've added some additional documentation for rate limiting (since this was brought up in issue #303 and I think the way that it's handled could cause some confusion) and updated the Makefile to be a little more user friendly (you can now build documentation locally and set up development environments or production environments as needed). There's also a contributing doc now, which (I hope) will allow people to get up to speed a little easier.

For the production environment, there's no testing dependencies, but installing responses and pytest allows the tests to be run and they all still pass. Additionally, due to some work before on the library, the `future` module is no longer a dependency since ``past.old_div``, which was only used on one line, is no longer needed. 

Since nose is no longer maintained, `py.test` is now used instead, with `pytest-cov` added as an additional dep. 

The README reflects the changes above.

@bear let me know if this is something you'd like to see in the library or I can keep working on it. I also tested out the config with readthedocs.org and it works fine over there with the previous updates to the docs which were merged a while back, so if you want to set that up, it should all work properly, even without this PR.

---
This change is [Review on Reviewable](https://reviewable.io/reviews/bear/python-twitter/304)

### CODE REVIEW

**Comment by bear** [comment]
completely agree with all of the above changes - especially the py.test change. thanks!

I would actually go a step further and remove any reference to ```sudo``` and ```virtualenv``` from the Makefile and include in the docs that people should use PyEnv to setup the working environment.

**Comment by jeremylow** [comment]
Cool; I had kind of been on the fence about pyenv (mostly extreme inertia against deviating from my old workflow), so this was a good opportunity to actually dig into it. Let me know if you agree with the changes to the Makefile and how things get set up. I rewrote the contributing section to show either an automated setup or going through the steps manually, so I hope that covers most use cases.

**Comment by bear** [comment]
To handle your scenarios above we should have the Makefile respect the environment variable ENV such that:

```ENV=production make env```

would run the production part of the env target, and 

```make env```

would run the development variant

**Comment by bear** [comment]
@jeremylow I'm making changes to the Makefile to enable circleci and also to upgrade the setup.py environment to be more modern.

I'll put what I was talking about above into the PR I am making so you can see

**Comment by jeremylow** [comment]
Gotcha. I just looked at your PR and that seems sensible. I'll close this PR and rebase off your work when it hits master. Sounds like a plan?

**Comment by bear** [comment]
that works for me if your ok with it

**Comment by jeremylow** [comment]
Let's do it.

**Pull request closed without merging**
