### PR TITLE
setup environment to be more modern; tweak Makefile; convert to CircleCI

### PR DESCRIPTION
**Pull request by bear**
This change is [Reviewable](https://reviewable.io/reviews/bear/python-twitter/308)

### CODE REVIEW

**Comment by jeremylow** [comment]
Would it be possible to add py3.5 to the tests? Currently only testing against 2.7.10.

**Comment by bear** [comment]
yes, will be adding them once I get everything looked at and +1'd from you for these changes

**Comment by jeremylow** [comment]
Looks good to me! The base commit from master is back a ways, but I assume that won't be a problem once merged.

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bear/python-twitter/308#-:-KD0ObTN-8dh-vGrh2n3:-643136077)*

**Comment by bear** [comment]
nope, the master differences was me forgetting to merge forward :)

merged with master and tweaked those things you had fixed that I broke (again) - thanks!

**Comment by bear** [comment]
@jeremylow I think I have covered the master merge issues and this should be ready to merge

**Comment by jeremylow** [comment]
Good to go from me. 

---

Review status: 8 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bear/python-twitter/308#-:-KD5daGCf7EXCknFEbGk:-824744049)*

**Comment by jeremylow** [comment]
Reviewed 4 of 4 files at r2, 2 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bear/python-twitter/308)*

**Comment by bear** [comment]
\o/ thanks!

**Pull request merged**
