### PR TITLE
Combining Models With Inheritence

### PR DESCRIPTION
**Pull request by jeremylow**
Hey @bear I don't know how you feel about this approach, but looking at the various objects for the Twitter data structures, I think most of them can be simplified down to inheriting from a single base class implementing a few different methods. This PR accomplishes that, but I would like to get your take on whether this is a good idea. 

The base class here is a TwitterModel object which implements generic versions of

* `__eq__` & `__ne__`
* `__str__`
* `AsDict`
* `AsJsonString`
* `NewFromJsonDict`

##### `__init__` Method
So for the `__init__` method, we set up a essentially a skeleton of default attributes for each class that should be able to be accessed without raising an `AttributeError` and that correspond to the attributes that we had before on each of the classes. A couple of these are updated with new attributes from Twitter (trends come to mind, with the addition of volume, etc.), but the value in them comes from having a base set of attribute available for the `AsDict` method. 

##### Equality methods
For the equality functions, we compare the AsDict methods, since the way it was implemented before, it seemed to me like you'd get a fair number of cases where two objects that are in fact equal compare to not equal. For instance, let's say you have two objects created with NewFromJsonDict (where ``resp`` is a json dict of a status):

```python
status1 = Status.NewFromJsonDict(resp)
status2 = Status.NewFromJsonDict(resp)
```

If you then delete, e.g., the ``id`` parameter from both of them:

```python
del(status1.id)
del(status2.id)
```

and then try to run an equality comparison on them:

```python
status1 == status2
>>> False
```

I think that operation should return ``True``. If you create and then perform the exact same operations on two objects, it seems to me like they should be considered equal. As it stands, this returns `False` because `Status.__eq__()` returns `False` on an `AttributeError` even if both objects raise the same `AttributeError` on the same attribute. 

##### AsDict
The `AsDict` method gets a little complicated in that some objects (Status, User) contain other objects which also inherit from the base class, meaning that calling `status.AsDict()` needs to have a ``dict`` object at the ``user`` key rather than a ``twitter.User`` object. This is accomplished by checking if the ``value`` at a given ``key`` inherits from `TwitterModel`. If it does, then the value, which is a subclass of TwitterModel, calls its AsDict method, thereby inserting a ``dict`` into the dictionary created by the initial call to ``Status.AsDict()``. 

(The whole thing with checking if the ``value`` is a list is only because there can be multiple ``twitter.Media`` objects contained in a ``twitter.Status`` object and we need to get a list and then have `Media.AsDict`'d object be the items in that list.)

The attributes that make up the constructed dictionary are only those that are contained in the ``self.params_default``, which gets set during ``__init__()``. I think this will simplify maintenance (and creation) of new classes (such as Collections hopefully), since you can specify what attributes you want to have a class set during creation and then that gets passed to the AsDict method without having to retype all of them twice. 

##### NewFromJsonDict
The only issue here is that some classes create other classes to assign to attributes. So, for example, a ``twitter.Status`` representing a tweet with a GIF in it contains a ``twitter.Media`` object (in a `list`; I don't know why `sets` were being used, but this can be swapped out) and a ``twitter.User`` object. I couldn't come up with a way of reliably dealing with the edge cases on this one without basically rewriting the method anyway, so that's what I did here. The default works for classes that don't contain other classes and everything else, you just override the method and call ``super`` at the end. From the looking at the tests, I _think_ that covers all of the edge cases.

##### Testing
Added the text of the tweet to the ``__repr__`` method, which is the only change to the test suite as it stands (there was a bug that I found wherein the AsDict method of Status was assigning a twitter.Media object to the media key of the dict, which broke the AsJsonString method, which required a change, but only because the previous behavior was broken). All of the tests at this point still pass without modification other than those noted above. Ideally, test coverage would be a little higher for better certainty that this doesn't break something, but otherwise, it looks OK in my applications. The new tests basically just ensure that nothing breaks on construction and method calls; only a few lines aren't covered by previous tests.

##### Properties
Since a change a while back in the setters and getters, most of the properties don't appear to be accessible. I don't know if I'm missing something here, but it seems like, per discussions elsewhere that these were an artifact (for the most part) from when the library was first written. They're easily added back in, but I think it's probably better long term to use the object attribute since there's not a lot of validation on the properties as it stands. 

-------------------

Sorry for the brain dump, but I wanted to get this down to integrate into some documentation if it's accepted. Any suggestions would be very welcome and I'm happy to continue work as needed.

---
This change is [Reviewable](https://reviewable.io/reviews/bear/python-twitter/312)

### CODE REVIEW

**Comment by bear** [comment]
I feel bad when you write such a great summary of why you want to make a change and give great examples... and then I respond +1 :)

yes, the object model reorg has been on my mind for a long time and was always set aside to fix other bugs or a lack of time, but I think now with all of the work you and others have been doing it is time to revisit it again.

The original *original* design was to have the classes generated by other code and that lead to a lot of items being easier to do one way but harder for humans to figure out. I would love to see each object be able to be defined as those items that make it different with all of the json/dict/list/error-handling bits hidden away in the base class.

Could we also take advantage of some of the newer dict-like classes that allow something to be referenced either as foo['bar'] or foo.bar ? - then we could hide deeper the asdict and asjson and expose only a .json helper method.

I don't see much of anything in your code above that I disagree with - so yea, +1

We should probably roll out a version with what we have and then target the above for v3

**Comment by bear** [comment]
Reviewed 27 of 27 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bear/python-twitter/312)*

**Comment by jeremylow** [comment]
Haha, see I think the point of a good description is to get to +1 faster, so I guess it works :) So just to make sure I get what you're saying: we should merge this PR for v3 and then continue to work on how best to organize for, say, v3.X or later, correct?

**Comment by bear** [comment]
yes please, v3 merge now and then iterate on best organization

thanks!

**Comment by jeremylow** [comment]
I'll update the docs to reflect changes (mostly I think it's just the linking conventions for Sphinx). Thanks!

**Pull request merged**
