### PR TITLE
Unicode support

### PR DESCRIPTION
**Pull request by jeremylow**
Model repr functions should work for py27 and py3 (using backslash escaped strings for py27 in JSON representations (i.e., `__str__` methods) and in `__repr__` methods). Closes issues #329 and #228. Tests for ``repr`` functions have been updated - since output is going to be different on py27 and py3, tests now just check to make sure that those functions don't raise exceptions.

Also fixed an issue with API encoding parameters properly for building URLs. For instance, building the search parameters when you had a UTF-8 `term` parameter for `GetSearch()` would result in a `UnicodeDecodeError`:

```python
>>> s = api.GetSearch(term="#ابشري_قابوس_جاء")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "twitter/api.py", line 426, in GetSearch
    resp = self._RequestUrl(url, 'GET', data=parameters)
  File "twitter/api.py", line 4514, in _RequestUrl
    url = self._BuildUrl(url, extra_params=data)
  File "twitter/api.py", line 4339, in _BuildUrl
    extra_query = self._EncodeParameters(extra_params)
  File "twitter/api.py", line 4393, in _EncodeParameters
    return urlencode(dict([(k, self._Encode(v)) for k, v in list(parameters.items()) if v is not None]))
  File "twitter/api.py", line 4375, in _Encode
    return str(s).encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd8 in position 1: ordinal not in range(128)
```

This closes issue #85. 

Adds a tox target for the Makefile if people want to use that - it made testing this stuff simpler, though that can be stripped out.

---
This change is [Reviewable](https://reviewable.io/reviews/bear/python-twitter/330)

### CODE REVIEW

**Comment by bear** [comment]
Reviewed 8 of 9 files at r1.
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[Makefile, line 14 \[r1\]](https://reviewable.io:443/reviews/bear/python-twitter/330#-KGmCmguHBoQriYDLf0f:-KGmC16T8Om0BogvrZZh:-1677114742) ([raw file](https://github.com/bear/python-twitter/blob/c2f5c7ab0e6129c1edf9e2826982afcc5c795afc/Makefile#L14)):*
since this is also in tox.ini isn't it redundant?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bear/python-twitter/330)*

**Comment by bear** [comment]
Reviewed 1 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bear/python-twitter/330)*

**Comment by jeremylow** [comment]
You'd think so, but pyenv requires the shell to be set to all versions that tox is going to run prior to calling calling tox. There's a bug that was filed against pyenv about it, but I'm comin up empty at the moment.  This might be a little too particular to my setup, so it might be better long run to remove the target and I can just run tox directly.

**Comment by bear** [comment]
go ahead and leave it in and file an issue with the pyenv issue referenced

then when it's fixed we can fix ours

**Comment by jeremylow** [comment]
OK, cool. I'll make a note of it and merge what we've got.

**Pull request merged**
