### PR TITLE
Add More Unit Tests

### PR DESCRIPTION
**Pull request by jeremylow**
## Description
Add unit tests for additional methods of API. Coverage increases to ~73%. API has a couple of changes to the newly tested methods: doc strings have been standardized in line with readthedocs (i.e., parameters get a `(type, [optional])`) and, where appropriate, type checking has been introduced for keyword arguments.

## Related Issue

No issue opened.

## How Has This Been Tested?

All new and old tests pass.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

---
This change is [Reviewable](https://reviewable.io/reviews/bear/python-twitter/385)

### CODE REVIEW

**Comment by jeremylow** [comment]
Getting this in the builds on CircleCI, which looks like it's preventing Codecov from updating:

```
CODECOV_TOKEN=`cat .codecov-token` codecov
cat: .codecov-token: No such file or directory
```

and this on the Codecov website:

```
  2016-09-15T06:38:30-04:00 upload  no-reports-generated  error=Error   
  2016-09-15T06:38:30-04:00 upload  True  error=Unknown-report   
  2016-09-15T06:38:30-04:00 upload  Upload archived download   
  2016-09-15T06:38:30-04:00 upload  GET /search/issues?q=d3b55813bf18f507407b738b4eac28adfdb4c08a+repo:bear%2Fpython-twitter+type:pr+state:open bot=bear code=200  ratelimit=29/30 reset=1473935970     
  2016-09-15T06:38:30-04:00 upload  GET /repos/bear/python-twitter/commits/d3b55813bf18f507407b738b4eac28adfdb4c08a bot=bear code=200     
  2016-09-15T06:38:30-04:00 upload  GET /repos/bear/python-twitter/contents/codecov.yml bot=bear code=404  
      {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}    
  2016-09-15T06:38:13-04:00  Upload accepted ci=circleci build=149.0   
```

**Comment by bear** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bear/python-twitter/385)*

**Comment by bear** [comment]
the `cat` is there to add the token for local test runs as I have multiple projects that use codecov and each have their own token :/ - so this is always going to error out unless we split it out to it's own make file target that checks for the `.codecov-token` as a dependency or something

**Comment by jeremylow** [comment]
Ah gotcha. That's cool. Let's just keep it as is. I think I figured out
what's causing the error on the codecov site (basically when I redid the
makefile in the last PR, it didn't run coverage - I'll do a fix over lunch
today).

-- 
Jeremy Low

**Comment by jeremylow** [comment]
Latest change runs coverage for each environment, stores the results in its own file (which is what the ``--parallel-mode`` does), and then combines them at the end for total coverage across all versions of python we test against (I was annoyed that version-specific code was being show as untested).

**Pull request merged**
