### PR TITLE
Using responses for testing purposes

### PR DESCRIPTION
**Pull request by jeremylow**
Hey @bear continuing from pull request #270 , I thought I'd open a new PR for using [responses](https://github.com/getsentry/responses) so that other folks might see it a little better and comment. The gist of how I structured the data for the tests is that, because there are lot of methods for the API, the best way to surface tests for each method in case something changes is to name the test function and data file name in accordance with the API, not the endpoint (the names of some of which are less than elucidating).

For example, `api.GetFavorites()` has a data file named `testdata/new/get_favorites.json` (the new part was just to keep things separate from the test data that was already in the repo), rather than `testdata/new/favorites/list.json`. I think this has the benefit that, if someone were to want to see what type of data is returned by the Twitter endpoint, there's a file containing that information that maps to the way to retrieve the data from `twitter.api`. Even though most all the endpoints are coded into the API as a `url` variable, my feeling is that it's easier to search for 'GetBlocks' in one file and look for 'url' (usually the first variable set) rather than look up the endpoint on dev.twitter and then search for that 'url' in the file, which is in at least one instance is not actually used (GetFollowers() I think).

-------------------------

In terms of use, each test tries to keep the same structure: open the data file (`with open('testdata/new/get_blocks.json'`), add an endpoint using responses (`responses.add(responses.GET[/POST]...`), and then make the API call (`resp = self.api.GetBlocks()`), and then either spot-check or test that the objects returned are of the expected types, etc.

I ended up using a hard-coded url for the `responses.add()` call; in retrospect I think those could use `self.api.base_url` and string formatting to build the endpoint since, if the base URL ever does change, then it's a single code change rather than many across a number of tests and files.

(Originally, I thought adding the URL to `responses.add()` would be as simple as parsing the `url` variable from the unbound instance of the API method, but, since some of the API methods set default variables, this isn't really an option. For example, although you can regex out the `url` variable from `api.GetBlocks` (through something like `api.GetBlocks.__code__.co_constants` by looking for a string starting with `'%s/'`), that method appends `?cursor=-1` when calling `api._RequestUrl` so responses won't catch the query string tacked onto the end.

(This also strikes me as a little too clever and I think confusing for anyone reading the tests or writing new ones, seeing as how you would have to know what's contained in `.co_constants`, which is not obvious from the name, then mentally parse the regex to figure out what the actual object of the search is, and then ensure that there's a variable named `url` in any new method (if you're writing one).))

------------------

As for the actual PR, there are a number of failing tests here; it's more of a proposal. A couple of parameters that get passed to Twitter changed (*i.e.*, `GetFollowersIDs()` I believe) and some of the methods were enforcing arguments that were optional according to Twitter (I'll submit a PR for those, but some of the other changes are breaking and I did not want to presume -- major changes documented [here](https://github.com/jeremylow/python-twitter/blob/python-v3/changelog.md) -- so the calls to those will fail).

In terms of adding a new dependency, I think adding an requirements file for that purpose is an accommodation, since responses will pull in a couple of dependencies itself and this keeps things clean for folks that aren't actively developing with the library.

[Review on Reviewable](https://reviewable.io/reviews/bear/python-twitter/273)

### CODE REVIEW

**Comment by bear** [comment]
@jeremylow much thanks for wading into this task!

I agree with most of what you have said above, and I think those items I don't agree with I just don't fully grok yet ;)

instead of doing this to the master, let me add you as a commitor and then you can create a branch to work in. this will also allow you to remove all of the failing tests and add them back in as the work is done.

sound like a plan?

**Comment by bear** [comment]
ok, your now listed as a collaborator!

I would suggest making a branch and then exploring the changes in it.

**Comment by jeremylow** [comment]
Sounds great! Thanks

**Comment by jeremylow** [comment]
I'm going to close this PR since most of the changes & tests have landed elsewhere.

**Pull request closed without merging**
