### PR TITLE
Update api.py

### PR DESCRIPTION
**Pull request by penn5**
Allow a list with one item to pass as a single item in the PostUpdate Image API

---
This change is [Reviewable](https://reviewable.io/reviews/bear/python-twitter/469)

### CODE REVIEW

**Comment by jeremylow** [comment]
Looks great, thanks!

**Comment by penn5** [comment]
Just noticed - it should stop processing media without an error if the list is empty! I'll add that to the pull request

**Comment by penn5** [comment]
Nevermind - it already does!

**Comment by bear** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bear/python-twitter/469)*

**Pull request merged**
