### PR TITLE
Honor 'count' parameter in API calls

### PR DESCRIPTION
**Pull request by rbpasker**
[Review on Reviewable](https://reviewable.io/reviews/bear/python-twitter/275)

### CODE REVIEW

**Comment by jeremylow** [comment]
Maybe add a kwarg `limit ` or `total`instead since redefining an already used kwarg, which is defined by twitter, is potentially confusing.

**Comment by rbpasker** [comment]
Also fixed a bug with GetFriendIDs

**Comment by bear** [comment]
+1 to @jeremylow 's request
also +1 to the suggested changes, @jeremylow can drive the merge

**Comment by rbpasker** [comment]
he's welcome to make whatever changes he wants

**Comment by bear** [comment]
It's a change that both of us could make, sure, but since it's a pull request from you and you are where it currently resides - it's much simpler for you to make that change.

**Comment by rbpasker** [comment]
I don't have time to work on anything right now, so I'll close the PR.

**Comment by bear** [comment]
not having time is, IMO, a valid pushback - let's leave this sit and see if @jeremylow has time before closing

**Comment by rbpasker** [comment]
i'm really sorry -- i am happy to do this at some future time, but just not right now

**Comment by jeremylow** [comment]
I'll take care of it; it's no problem at all.

**Comment by bear** [comment]
apologies if my reply came across as being cross or grumpy - I truly believe that any help given in any manner is something to be enjoyed and celebrated, so apologies if that reply came across badly.

we all give time to projects as we can and I am thankful for any time given

**Comment by jeremylow** [comment]
So I looked into this tonight and I think there's going to be some unavoidable confusion since Twitter uses the parameter 'count' for two different things:

* For the endpoints `/followers/list.json` and `friends/list.json`, `count` denotes how many users to return per page (or cursor call, if you want to think about it that way).
* For the endpoints `/followers/ids.json` and `friends/ids.json`, `count` denotes the upper bound of the total number of users that should be returned (i.e., for `count=50` you're only guaranteed to *not get more than* 50 users).

In an ideal world, that'd not be true, and the latter would be something like `limit`, but it is what it is. Since this library already has a couple of convenience functions, I think that the arguments passed to these four endpoints should remain as they are defined by Twitter and python-twitter should layer convenience keywords on top of that. (That's probably least disruptive to existing code? Especially if the current implementation is a little wonky anyhow.)

I'm going to work on this some more this week, but wanted to at least get some thoughts down.

**Comment by rbpasker** [comment]
a few points:
1. GetFollowers and GetFriends should not have a `count` parameter the page (or batch) size. Instead they should take **kwargs, and pass those on to their *Paged brethren. 
2. GetFollowers and GetFriends should not take `cursor` since they return the entire friends or followers list.
3. None of the `count` parameters should have or imply a default value, since twitter may increase or decrease the count at its API level, which may leave the program not working (say, if twitter lowers the max value of `count` from 5,000 to 2,500) or suboptimal (if twitter raises the max value of count from `5000` to `10000`).
4. GetFollowers and GetFriends should have a parameter `limit` to indicate the max number to return
5. GetFollowers and GetFriends should take an optional parameter like `should_sleep` to indicate that the caller wants to sleep and retry. otherwise they return with however many they could get without sleeping (which may be 0).
6. note that there's a subtlety in the sleep logic: if I call GetFriends with an exhausted rate limit, then it will raise a rate limit exception, but if I call it with rate-limit of 1, it'll make one call and then sleep. I think the uniform behavior would be for GetFriends and GetFollowers to sleep & retry if called with an exhausted rate limit

**Comment by rbpasker** [comment]
I think that the arguments passed to these four endpoints should remain as they are defined by Twitter

I think the low-level APIs (*Paged) that make REST calls directly should take the Twitter-defined `count` parameters, and the higher-level APIs (non-*Paged) should use `limit`.

**Comment by jeremylow** [comment]
Hey Bob,

1. Is the suggestion that `GetFriends()` take something like `GetFriends(screen_name='jack', **kwargs)`? (My only concern with this is that the documentation for python-twitter is, er, a little light, so to the end user it might be a matter of having to google or look at the source code to see what keyword arguments are valid.)
3. I think `count` can have a default value in the library that's different from Twitter's default, which saves folks from having to specify it. Also, since we can specify a higher default, we can save round trips and rate-limited calls to the API. At the moment, if you try to set `count` to, say, 2000, the API just returns its default `count` (which is 20). 

One change that I made from yesterday is that the check for `limit` occurs before the last call in the `while True` loop, so that you always return less-than-or-equal-to the `limit` param.

Thanks for the suggestions; I'll keep working on getting the code in place. (Turns out there isn't a GetFriendsPaged.)

**Comment by rbpasker** [comment]
using kwargs seems to be pythonic when one library function passes most of its args to another. you can always use docstrings to clarify

Regarding #2, how does a library designer go about picking the proper default for 'count'? 

I don't have a horse in this race, so carry on

**Comment by bear** [comment]
my thoughts, which can/should be ignored :), is that we should follow the patterns for public facing api calls to match twitter but can do anything we need/want for internals -- just document the heck out of it.

shipping working code trumps all

**Pull request merged**
