### PR TITLE
Update tweet.py

### PR DESCRIPTION
**Pull request by PistachioPony**
added the updated way of printing if the user is coding in python3 (commented out)

---
This change is [Reviewable](https://reviewable.io/reviews/bear/python-twitter/447)

### CODE REVIEW

**Comment by jeremylow** [comment]
You could also do a `from __future__ import print_function` and then: `print("{0} just posted: {1}".format(status.user.name, status.text))` for py2/py3 compatibility.

**Comment by PistachioPony** [comment]
Nice! I updated my patch

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/bear/python-twitter/447#-:-Ke0sHrSX3ZEtAdr75Du:b-k60gqv)*

**Comment by jeremylow** [comment]
Hey, sorry for being so late on getting back to you on this. There are a couple things left:

* Need to move the __future__ import to the top of the import list
* There are still some lingering old style print functions hanging around which need to be changed to the new style.

Other than that, we should be good to go.

**Comment by PistachioPony** [comment]
No worries, I'm on it and happy to help!

**Comment by johnwmillr** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bear/python-twitter/447)*

**Pull request merged**
