### PR TITLE
Changes to tweet counting

### PR DESCRIPTION
**Pull request by jeremylow**
## Description

Changes update the API to be compliant with the REST portions of the changes described here: https://dev.twitter.com/overview/api/upcoming-changes-to-tweets . There is a new `tweet_mode` parameter for choosing whether to remain in compatibility mode (i.e., the old mode, but tweets may be truncated) or in the new, shiny `extended_mode`. Documentation has been updated, though it's a little rough at the moment while we see how things shake out from Twitter.

Additionally, I fixed the regex a little bit for the URL parsing to better match that of Twitter. It's not perfect; see 0180e2785ed19ca48d3b15011b33bb87df8a6e48 for details.

This is not a breaking change.

## Related Issue

Issue #338 
Issue #346 

## Motivation and Context

Changes are required for new `extended_mode` 

## How Has This Been Tested?

Most tests had to be rewritten for the updates, as a new query parameter (`tweet_mode`) is getting passed to Twitter with most of the GET requests. Changes have been tested, though I'd like to see better coverage for what's changed to make sure we're not missing something.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

---
This change is [Reviewable](https://reviewable.io/reviews/bear/python-twitter/394)

### CODE REVIEW

**Comment by jeremylow** [comment]
@bear any thoughts?

**Comment by bear** [comment]
Reviewed 24 of 24 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bear/python-twitter/394)*

**Comment by bear** [comment]
I am loving all the tests and changes - apologies for not looking at this soo much sooner

**Comment by jeremylow** [comment]
Awesome! Yeah - I think the changes to the tests will make it a whole lot easier to maintain going forward.

**Pull request merged**
