### PR TITLE
Docs config two

### PR DESCRIPTION
**Pull request by jeremylow**
Basically the same PR as #304, but without the changes to the Makefile and all the pyenv/pytest changes, since those were included in #308. 

Where applicable, the documentation's been revised in accordance with the changes in #308 that differed from the proposed changes in 304.

---
This change is [Reviewable](https://reviewable.io/reviews/bear/python-twitter/309)

### CODE REVIEW

**Comment by bear** [comment]
:lgtm: thanks for taking on the docs and making them accurate!

---

Review status: 0 of 34 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bear/python-twitter/309#-:-KDL8gd7zSve5aEfFBl7:709149443)*

**Comment by bear** [comment]
Reviewed 1 of 34 files at r1.
Review status: 1 of 34 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bear/python-twitter/309)*

**Comment by bear** [comment]
Reviewed 33 of 34 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bear/python-twitter/309)*

**Comment by jeremylow** [comment]
Cool. Thanks!

**Pull request merged**
