### PR TITLE
Adds support for 280 character tweet limit

### PR DESCRIPTION
**Pull request by trevorprater**
- Tested and working. Passes 100% of tests.
- Bumps version from 3.3 -> 3.3.1

---
This change is [Reviewable](https://reviewable.io/reviews/bear/python-twitter/525)

### CODE REVIEW

**Comment by dmerejkowsky** [comment]
Looks good to me :)

**Comment by trevorprater** [comment]
_bump_

**Comment by jeremylow** [comment]
Needs to bump version in `twitter/__init__.py` as well. Otherwise, looks great.

**Comment by trevorprater** [comment]
Thank you, @jeremylow, @dmerejkowsky ,

I have [bumped](https://github.com/bear/python-twitter/pull/525/commits/75d7d21e7add1a94f37a081869b5b2279a238c1c) the version.

**Comment by justerson** [comment]
I'm waiting to use this to upgrade an app I've written, but it doesn't seem to be in the pip repo. When will the 3.3.1 distribution be available via pip? Appreciate the work on this!

**Comment by justerson** [comment]
@jeremylow Any idea when this will be updated in the Python repo?

**Comment by family-guy** [comment]
would also be a big help to me if the new version is made available in pip for the new character limit. Will this be done soon? Or could I be given access to do it myself? Thanks

**Comment by jeremylow** [comment]
Release will be soon; probably this weekend. https://github.com/bear/python-twitter/issues/516

**Pull request merged**
