### PR TITLE
Proxy settings feature added

### PR DESCRIPTION
**Pull request by mkdadi**
This change is [Reviewable](https://reviewable.io/reviews/bear/python-twitter/449)

### CODE REVIEW

**Comment by jeremylow** [comment]
I have some concerns with this approach. 

* `requests` can read proxy information from environment variables as explained here: http://docs.python-requests.org/en/master/user/advanced/#proxies , which seems like the simplest approach to adding proxy support since that's just a documentation change pointing out that that's available.

* rather than adding a new keyword argument to each method (and then remembering to do that on all future methods), we could do something where we add a `proxies` kwarg to the Api instantiation and then have that be available to `Api._RequestUrl()` etc. as `self.proxies`.

**Comment by mkdadi** [comment]
I agree that `requests` can read the proxy information from environment variables but if I want only this api to run through proxy I thought this would help. And yes you are correct rather that adding it to every method, it would have been better if an attribute is added to the class, Thanks.

**Comment by mkdadi** [comment]
Inline documentation for the parameter has been added. Thanks.

**Comment by mkdadi** [comment]
Done :+1:

**Pull request merged**
